### ISSUE TITLE
Sample app compilation issues - Missing xcconfig and no such module

### ISSUE THREAD

**Issue by mattmook** [icerockdev/moko-kswift#12]
When opening the iOS workspace for the first time, you see the following errors:

<img width="621" alt="image" src="https://user-images.githubusercontent.com/182422/129438168-d68d9da1-4dfd-4acc-baed-59e2757ea0b0.png">

It would be useful to have better documentation around getting the sample compiling, as this error can easily be fixed by running `pod install`.

The next issue I hit is:

<img width="616" alt="image" src="https://user-images.githubusercontent.com/182422/129438394-1435dc62-cb5b-448b-9fa4-2cdac41f090b.png">

This occurs regardless of running `./gradlew build`

**Comment by Alex009** [comment]
hi!
here my steps for local development:
```
# clone repo
git clone git@github.com:icerockdev/moko-kswift.git
cd moko-kswift 
# generate podspec files for cocopods intergration. with integration will be generated swift files for cocoapod
./gradlew kSwiftmpp_library_podsPodspec
./gradlew kSwiftMultiPlatformLibraryPodspec
# go to ios dir
cd sample/ios-app
# install pods
pod install
# now we can open xcworkspace and build ios project
open ios-app.xcworkspace
# or run xcodebuild
xcodebuild -scheme ios-app -workspace ios-app.xcworkspace test -destination "platform=iOS Simulator,name=iPhone 12 mini"
xcodebuild -scheme pods-test -workspace ios-app.xcworkspace test -destination "platform=iOS Simulator,name=iPhone 12 mini"
```

by this steps you should got correct setup

**Comment by mattmook** [comment]
Thanks @Alex009 the new instructions work like a treat
