### ISSUE TITLE
No signature of method: kswift() is applicable for argument types

### ISSUE THREAD

**Issue by mMaxy** [icerockdev/moko-kswift#14]
Hi! 
I tried to follow installation guide. 
I've added to my settings.gradle
```
    gradlePluginPortal()
    maven { url "https://jitpack.io" }
```
and to my build.gradle
```
buildscript {
    repositories {
        gradlePluginPortal()
        maven { url "https://jitpack.io" }
    }
}

plugins {
    id 'dev.icerock.moko.kswift' version '0.2.0'
}

kswift {
    install(dev.icerock.moko.kswift.plugin.feature.SealedToSwiftEnumFeature) 
}
```

And after that gradle throws me an error, pointing to line with 'intsall(': 
```
> No signature of method: build_4x81nw95mougfd7sujytehczz.kswift() is applicable for argument types: (build_4x81nw95mougfd7sujytehczz$_run_closure3) values: [build_4x81nw95mougfd7sujytehczz$_run_closure3@381aa491]
  Possible solutions: notify(), wait(), wait(long), print(java.lang.Object), with(groovy.lang.Closure), split(groovy.lang.Closure)
```

I am using Gradle 6.8.2, Kotlin 1.5.21. Same error if I switch to gradle 7.0.2.

I'm really out of ideas what happening. Maybe you can help?

**Comment by Alex009** [comment]
hi! it seems that in groovy our plugin API not valid... for now you can try build.gradle.kts version.
also we will check api on groovy and fix it

**Comment by Alex009** [comment]
in version 0.3.0 added support of groovy configurations, sample will be in readme
