### ISSUE TITLE
Enhancement: Generate extensions over primitive types

### ISSUE THREAD

**Issue by PStrelchenko** [icerockdev/moko-kswift#22]
## Plugin version I've used

```kotlin
plugins {
    id("dev.icerock.moko.kswift") version "0.3.0"
}
```

## Problem

If we define extension function over, e.g. `String` type in Kotlin, this function will not be translated as an extension in Swift:

```kotlin
// StringExt.kt

val String.myExtensionProperty: String get() = "123"
fun String.myExtensionFunction() { ... }

private fun example() {
    val result = "123".myExtensionProperty
    "123".myExtensionFunction()
}
```

`moko-kwift` didn't handle this issue, because [extension function didn't pass the filter](https://github.com/icerockdev/moko-kswift/blob/master/kswift-gradle-plugin/src/main/kotlin/dev/icerock/moko/kswift/plugin/feature/PlatformExtensionFunctionsFeature.kt#L89-L110) =)

It would be great if moko-kswift will generate extensions in such case.

**Comment by Alex009** [comment]
will be available in 0.4.0
