### ISSUE TITLE
Duplicate module names overwrite

### ISSUE THREAD

**Issue by PaulWoitaschek** [icerockdev/moko-kswift#24]
We have a gradle module structure like:

featX:ui
featX:data
featY:ui
featY:data

And an umbrealla module consuming all other modules for iOS. Currently the task generates swift files having the module name and not the path of the module.
This leads to a single `ui.swift` of the last module in the compilation overwriting all other `ui.swift` modules.

It would be good if that would not happen and the whole module path would be used for the swift name, for example:
`featY_ui.swift`, `featX_ui.swift`

I'm using 0.3.0

**Comment by Alex009** [comment]
will be available in 0.4.0
