### ISSUE TITLE
Generated Swift file should use `KotlinThrowable` instead of `Throwable`

### ISSUE THREAD

**Issue by kittinunf** [icerockdev/moko-kswift#25]
Hey, first of all, thanks for this library and the others useful libraries. As a KMM passionated developer, I am very happy to see that you and your team at `icerockdev` are pushing KMM to the limit 😄 👍 

While I am working on the Swift bridging with moko-kswift, I found out that the generated file use "regular" `Throwable` instead of `KotlinThrowable` which result in compiling error at the Client side.

<img width="704" alt="Screen Shot 2021-09-24 at 13 38 03" src="https://user-images.githubusercontent.com/4669517/134619063-a833ce14-4547-4172-8d76-f71edb047eca.png">

This is the generated `.h` content from the Kotlin Native side.

This looks like a bug to me, or I was wondering whether I am missing anything here?

**Comment by Alex009** [comment]
will be available in 0.4.0
