### ISSUE TITLE
Generate extensions over extension methods for Companion object

### ISSUE THREAD

**Issue by jeantuffier** [icerockdev/moko-kswift#31]
It seems like no swift code is generated for this function :
```
fun CostAttributes.Companion.fromDailyEntries(
    today: DailyEntries,
    yesterday: DailyEntries? = null,
    now: String = Clock.System.now().toString()
) = ...
```

Same  things with many other extensions on other companion objects I have

**Comment by Alex009** [comment]
hi!
as i see Kotlin/Native successful generate extensions for companion without any additions.

i test on:
```
class SomeClass {
    companion object
}

fun SomeClass.Companion.extensionOnCompanion() = Unit

fun SomeClass.extensionOnKotlinClass() = Unit

fun IntProgression.Companion.extensionOnKotlinCompanion() = Unit
```

in all cases i got extensions already available in `SomeClass`, `SomeClass.Companion`, `IntProgression.Companion` api.

**Comment by jeantuffier** [comment]
Alright, I need to check again and reports what I found.
