### ISSUE TITLE
Unable to resolve a Gradle plugin

### ISSUE THREAD

**Issue by amatsegor** [icerockdev/moko-kswift#4]
Hi there!
I've followed an installation guide, added needed repo-s into my project-root build.gradle.kts file, but when I try to Sync the project, I get this:

Caused by: org.gradle.internal.resolve.ModuleVersionNotFoundException: Could not find dev.icerock.moko:kswift-gradle-plugin:0.1.0.
Searched in the following locations:
  - https://dl.google.com/dl/android/maven2/dev/icerock/moko/kswift-gradle-plugin/0.1.0/kswift-gradle-plugin-0.1.0.pom
  - https://repo.maven.apache.org/maven2/dev/icerock/moko/kswift-gradle-plugin/0.1.0/kswift-gradle-plugin-0.1.0.pom
  - https://maven.pkg.jetbrains.space/kotlin/p/kotlin/kotlin-dependencies/dev/icerock/moko/kswift-gradle-plugin/0.1.0/kswift-gradle-plugin-0.1.0.pom
  - https://jitpack.io/dev/icerock/moko/kswift-gradle-plugin/0.1.0/kswift-gradle-plugin-0.1.0.pom

**Comment by Alex009** [comment]
hi!
as i see - you lost `gradlePluginPortal()` in repositories list

**Comment by amatsegor** [comment]
@Alex009 exactly, my bad. Thanks!
