### ISSUE TITLE
How to integrate with other Moko libraries

### ISSUE THREAD

**Issue by Narek1994** [icerockdev/moko-kswift#45]
Hi, can someone help me to understand how this type of intergration should look alike, I have done everything written in Setup part, but checking with Sample app there is a completely different structure compared with mine.

Here is my plugins and dependencies list

![Screen Shot 2022-05-20 at 17 27 07](https://user-images.githubusercontent.com/29127973/169537874-35ff4083-42e1-422a-9c73-2a3e37cc18c1.png)

And here is Kswift configuration part.

![Screen Shot 2022-05-20 at 17 25 21](https://user-images.githubusercontent.com/29127973/169537521-1fe450b4-7fac-4761-aa09-49207914f492.png)

After that it generates shared.podspec, file 

![Screen Shot 2022-05-20 at 17 28 32](https://user-images.githubusercontent.com/29127973/169538138-720041d1-6873-4dbc-9030-70e0e1643656.png)

and pod successfully installs, but I dont get any generated file in my source code. Not for sealed classes and not for any binding extensions.
Can someone help me to understand what I am doing wrong.

**Comment by Alex009** [comment]
hi. generated swift code not included into Kotlin framework. generated code can be added to Xcode directly via "Add files..." (location of files described [here](https://github.com/icerockdev/moko-kswift#where-destination-directory-for-all-generated-sources)) or by adding second cocoapod - `sharedSwift`. podspec of `sharedSwift` generates by gradle task of kswift - `kSwiftSharedPodspec`.

here sample with direct files - https://github.com/Alex009/moko-kswift-usage-sample/tree/regular-framework
another sample with direct files - https://github.com/Alex009/moko-paging-sample
sample with cocoapods - https://github.com/icerockdev/moko-kswift/tree/master/sample/mpp-library-pods

**Comment by Narek1994** [comment]
Thanks, figured it out with cocoapods!
