### ISSUE TITLE
Using with regular framework

### ISSUE THREAD

**Issue by ychescale9** [icerockdev/moko-kswift#5]
👋 

I'm using `:embedAndSignAppleFrameworkForXcode` to build a regular framework instead of using Cocoapods.

I can see the generated `.swift` sources available in `build/xcode-framework/$(CONFIGURATION)/$(SDK_NAME)` but I can't reference them from the iOS project. Is there anything manual process that needs to be done here?

**Comment by Alex009** [comment]
hi! for regular framework at now i suggest next approach:
add copy action to Link tasks, so after each compilation of kotlin/native all generated sources will be moved to your directory.
```kotlin
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinNativeLink>().matching {
    it.binary is org.jetbrains.kotlin.gradle.plugin.mpp.Framework
}.configureEach {
    doLast {
        val swiftDirectory = File(destinationDir, "${binary.baseName}Swift")
        val xcodeSwiftDirectory = File(buildDir, "generated/swift")
        swiftDirectory.copyRecursively(xcodeSwiftDirectory, overwrite = true)
    }
}
```
and add this directory into xcode project by "add files".
see my sample - https://github.com/Alex009/moko-kswift-usage-sample/tree/regular-framework
and here commit with integration - https://github.com/Alex009/moko-kswift-usage-sample/commit/fc921315acb4baa06cbb6038bcd77a639cb329b0

**Comment by ychescale9** [comment]
Thanks!

**Comment by prvaghasiya** [comment]
Sample does not compile in Apple M1 mac

Also, when I use this workaround in latest KMM template from Android Studio. destinationDir id not defined, looks like it is removed. I am not able to generate these classes. Can you please help?

**Comment by prvaghasiya** [comment]
Ok this works with replacing `destinationDir` to `outputFile.get()` Thanks to [PR](https://github.com/icerockdev/moko-kswift/commit/33ed6da3503d7e85788586d22f867147a41e300b)

Full snippet
```
tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinNativeLink>().matching {
    it.binary is org.jetbrains.kotlin.gradle.plugin.mpp.Framework
}.configureEach {
    doLast {
        val swiftDirectory = File(outputFile.get(), "${binary.baseName}Swift")
        val xcodeSwiftDirectory = File(buildDir, "generated/swift")
        swiftDirectory.copyRecursively(xcodeSwiftDirectory, overwrite = true)
    }
}
```

However, Moko classes are not being generated in case of latest XCFramework syntax

```
kotlinArtifacts {
        Native.XCFramework("BL") {
             targets(iosArm64)
             modes(DEBUG)
            // dynamic framework
            isStatic = false
            // disable bitcode, anyway Xcode 14 does not need it
            embedBitcode = EmbedBitcodeMode.DISABLE
        }
    }
}
```
