### ISSUE TITLE
kotlin 1.7.0 support

### ISSUE THREAD

**Issue by Alex009** [icerockdev/moko-kswift#53]
@Alex009, thanks, sure, I managed to reproduce by adding kswift to the project, [sample here](https://github.com/aleksey-ho/moko-resources-sample)
gradle build is successful, but xcode build fails

_Originally posted by @aleksey-ho in https://github.com/icerockdev/moko-resources/issues/358#issuecomment-1183951009_

**Comment by Alex009** [comment]
https://github.com/icerockdev/moko-kswift/issues/51#issue-1268726206 also

**Comment by burakeregar** [comment]
Hi @Alex009, do you happen to have any rough ETA on this?

**Comment by Alex009** [comment]
will be released in 0.6.0

**Comment by Alex009** [comment]
You got some errors on latest kotlin with latest kswift?

**Comment by antanas-radzevicius-tgo** [comment]
having same problem on latest kotlin version with isStatic =having same problem with latest kotlin and kswift version when cocoapods flag isStatic = true
