### ISSUE TITLE
It is possible to exclude all by default?

### ISSUE THREAD

**Issue by franmontiel** [icerockdev/moko-kswift#54]
I want to exclude all classes minus the ones included via annotations or via gradle configuration. 

I do not find a way to do it. Is it possible with the current implementation?

Thanks a lot.

**Comment by Alex009** [comment]
hi @franmontiel ! plugin have two ways for filters:
- include by default with exclude list
- exclude by default with include list

for your case required second filter.
sample:
```
kswift {
    install(dev.icerock.moko.kswift.plugin.feature.SealedToSwiftEnumFeature) {
        filter = includeFilter("ClassContext/moko-kswift.sample:mpp-library-pods/com/icerockdev/library/UIState")
    }
}
```
with this gradle config generation will be only for `UIState` class. all other classes will be skipped

**Comment by franmontiel** [comment]
Thanks, for some reason I was thinking that was not the behavior. Tested again and everything is working as expected.
