### ISSUE TITLE
Gradle Sync deletes generated KSwift files

### ISSUE THREAD

**Issue by shubhamsinghshubham777** [icerockdev/moko-kswift#68]
Hi here!
First of all I want to thank the team who made this plugin possible, it's really useful 🌟

Now, I'm not sure if this is an issue of the plugin or gradle itself (or maybe I'm not setting up the plugin correctly) but whenever I make some updates to the `build.gradle` of the `shared` module (where I have set up kswift as well) and click on the `Sync now` button (or even just restart IntelliJ IDEA and it automatically syncs gradle), it deletes the existing `shared/build/cocoapods/framework/sharedSwift` folder that won't be generated until I do the following:

**Starting point:** After gradle sync, the `sharedSwift` folder is no longer present
<img width="1512" alt="Screenshot 2022-12-28 at 9 26 15 AM" src="https://user-images.githubusercontent.com/46640516/209754929-677e930c-091c-4840-bf69-008bc9aa3f20.png">

**Step 1:** Go to XCode and run the app until the build fails due to `sharedSwift` not being available anymore
<img width="1512" alt="Screenshot 2022-12-28 at 9 30 09 AM" src="https://user-images.githubusercontent.com/46640516/209755196-6e02cd5c-0cff-4b3a-aa83-07fc8f4c86f9.png">

**Step 2:** Come back to IntellJ IDEA, open the terminal, ensure that the `sharedSwift` folder is generated now and then run `pod install` in its terminal
<img width="1512" alt="Screenshot 2022-12-28 at 9 32 11 AM" src="https://user-images.githubusercontent.com/46640516/209755357-bcb1a3a9-7a70-4122-abbe-891263567b44.png">

**Step 3:** Go back to XCode, and from the popup, select `Read from disk` to make sure XCode reads the newly generated files
<img width="1512" alt="Screenshot 2022-12-28 at 9 32 37 AM" src="https://user-images.githubusercontent.com/46640516/209755383-09d72cea-2ac1-4dc5-aa56-52aaf2081d14.png">

**Step 4:** Let `Step 3` finish its build completely and then the app `run/build` would finally succeed
<img width="1512" alt="Screenshot 2022-12-28 at 9 34 53 AM" src="https://user-images.githubusercontent.com/46640516/209755576-6b61cb77-a20e-437e-8923-3e5858e9ebe6.png">

This becomes quite tedious while developing 😅 Therefore I want to ask if there's a way to retain the previously generated files inside the `build` folder every time we sync gradle (or manually allow the generation of these generated files)?

**Comment by Alex009** [comment]
hi!
when after `pod install` you see that generated swift file shows in pods dir as here

![](https://user-images.githubusercontent.com/46640516/209755576-6b61cb77-a20e-437e-8923-3e5858e9ebe6.png)

you should not use `pod install` anymore and deletion of geenrated files after gradle sync not affect your xcode. when you build app in xcode - framework will be automatically compiled and kswift code will be generated too, so all will be compiled successful.

i agree that integration flow now is complicated, but at now i not see some better way yet

**Comment by shubhamsinghshubham777** [comment]
Understood. Thanks for the response @Alex009 
Closing this issue for now ✅
