### ISSUE TITLE
Files for external libraries generate with errors

### ISSUE THREAD

**Issue by sed0** [icerockdev/moko-kswift#73]
Hello! We need kswift to generate files for external libraries but it's generating files with these errors:
"Cannot find type 'ClassName' in scope" and "No type named 'ClassName' in module 'shared'"

The generated files are ok but it looks like the libraries are inaccessible in ios/swift for some reason.
We use kswift with default settings in a number of projects and all of the external lib files are generated with this issue

**Comment by Alex009** [comment]
hi! external libraries should be exported in framework settings to use from swift.
https://kotlinlang.org/docs/multiplatform-build-native-binaries.html#export-dependencies-to-binaries

also you can add `excludeLibrary` in gradle to not generate code that you will not use
