### ISSUE TITLE
Is it necessary to name a multiplatform lib exactly 'MultiPlatform Library'

### ISSUE THREAD

**Issue by romanandreyvich** [icerockdev/moko-kswift#76]
My KMM lib has a name different of 'MultiPlatformLibrary'

After I compile iOS project I got the error: No such module 'MultiPlatformLibrary'
![1](https://user-images.githubusercontent.com/15000414/228918043-f47c0097-be33-4dd4-aa91-31fd7b816ace.png)

Is there any option to use moko-kswift with custom KMM lib name?

**Comment by Alex009** [comment]
kswift works with any framework name.

in your screenshot i see not KSwift generated code, but mokoMvvmFlowSwiftUI module. check readme in moko-mvvm https://github.com/icerockdev/moko-mvvm#swiftui-additions
short: to use precompiled `mokoMvvmFlowSwiftUI` your module should have name `MultiPlatformLibrary` but you can copy-paste swift sources of this module to your project https://github.com/icerockdev/moko-mvvm/issues/179#issuecomment-1119254946

**Comment by romanandreyvich** [comment]
Oh, I got it :) Thanks for your help
